/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wesai_mygame_Utils */

#ifndef _Included_com_wesai_mygame_utils
#define _Included_com_wesai_mygame_utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wesai_mygame_Utils
 * Method:    postMsg2Cocos
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wesai_mygame_Utils_postMsg2Cocos
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif